### ISSUE TITLE
plex_lex calling plex_prepare without using value returned by plex_prepare

### ISSUE THREAD

**Issue by FreeBASIC-programmer** [phorward/phorward#17]
I am experimenting with an alternative internal format for the dfa and found two lines of code in plex_lex that looked suspicious. 
Before calling plex_lex a user is supposed to call plex_prepare. Failing to do so does will lead to the the execution of the following lines of code (line 251, plex_lex):
```
if( !lex->trans_cnt )
  plex_prepare( lex );
```
After the call to plex_prepare scanning commences as-if plex_prepare succeeded in creating a dfa.
But what if it fails? There will be a problem when plex_lex tries to use lex->trans if trans was not created (which is the case when plex_prepare returns FALSE).

I found exactly the same lines of code as the ones shown above in plex_next. So if there is a problem with plex_lex then there is a problem with plex_next as well.

I hope I have found a bug. If not then I humbly apologize for misinterpreting your code.

**Comment by phorward** [comment]
Hi @FreeBASIC-programmer,
yes, in that case I assumed that plex_prepare() never fails, even though it could, so you're right, it must be checked. I've done a fix for it in 69ad7fa, so it should be better now :-)

Thanks!
