### ISSUE TITLE
Typos in files

### ISSUE THREAD

**Issue by FreeBASIC-programmer** [phorward/phorward#3]
I found typos in a bunch of files. (Most if not all) of the typos have to do with the use of the word trough (=>through).

https://github.com/phorward/phorward/blob/fc7c7bcffd1d2737627c93043aae77e317447daf/src/base/array.h#L30
trough => through 

The whole construct can be rewritten (iterating through and iterating are equivalent). 
```
Macro that expands into a for-loop iterating a parray-object
```
Same thing in 
https://github.com/phorward/phorward/blob/fc7c7bcffd1d2737627c93043aae77e317447daf/src/base/list.h#L67

https://github.com/phorward/phorward/blob/91eaf8e1f44bcc013d3f4c57a20ca736542cfbe8/src/regex/misc.c#L55
trough => through

https://github.com/phorward/phorward/blob/91eaf8e1f44bcc013d3f4c57a20ca736542cfbe8/src/parse/gram.c#L370
trough => through

https://github.com/phorward/phorward/blob/91eaf8e1f44bcc013d3f4c57a20ca736542cfbe8/src/parse/gram.c#L523
trough => through

https://github.com/phorward/phorward/blob/91eaf8e1f44bcc013d3f4c57a20ca736542cfbe8/src/any/any.c#L115
trough => through

https://github.com/phorward/phorward/blob/712f9b21d8b7bd733783b44254c5198e1ecb4dc4/src/regex/nfa.c#L263
https://github.com/phorward/phorward/blob/712f9b21d8b7bd733783b44254c5198e1ecb4dc4/src/regex/nfa.c#L325

trough => through

https://github.com/phorward/phorward/blob/e709b9e6901257d04bd9a212e8a0175499781512/doc/phorward.t2t#L191

trough => throughout and with a bit of a rewrite you get
```
These functions are used throughout libphorward's internal object mapping functions.
```

https://github.com/phorward/phorward/blob/712f9b21d8b7bd733783b44254c5198e1ecb4dc4/src/regex/ptn.c#L510

Again trough => through. After a rewrite you get
```
/* Iterate ccl... */
```
Iterate implies 'accessing every element in'. The above could be read as 'access every element in ccl' which is what you want to convey.

https://github.com/phorward/phorward/blob/e709b9e6901257d04bd9a212e8a0175499781512/doc/ref.t2t#L121
https://github.com/phorward/phorward/blob/e709b9e6901257d04bd9a212e8a0175499781512/doc/ref.t2t#L156

In both of the above cases you could use
```
Macro that expands into a for-loop iterating a 
```

https://github.com/phorward/phorward/blob/e709b9e6901257d04bd9a212e8a0175499781512/doc/phorward.html#L1005

rewrite (same as before)
```
These functions are used throughout libphorward's internal object mapping functions.
```

https://github.com/phorward/phorward/blob/e709b9e6901257d04bd9a212e8a0175499781512/doc/phorward.html#L2684

rewrite (same as before)
```
Macro that expands into a for-loop iterating a parray-object
```

I still have to test your bug - fix (plex_tokenize). I looked at the fix and thought: looks good to me and forgot to download/test. I'd be surprised if there would be a problem with the fix. I will download and test the fix regardless. I tried plex_tokenize in the first place because I wanted to see whether calling plex_tokenize once would result in faster lexing than calling plex_lex for each and every token.

**Comment by phorward** [comment]
Hello @FreeBASIC-programmer, again many thanks for your useful help, I fixed all typos in 54f827a.

The documentation is generated from the source code, so there was no need to change all locations, only the sources and re-generating the docs. I replaced all "trough" by "through" using this [tiny shell script](https://gist.github.com/phorward/3a3824818463cbd3f3d2f4296356567b).
