### ISSUE TITLE
Example (C scanner) and a question

### ISSUE THREAD

**Issue by FreeBASIC-programmer** [phorward/phorward#4]
I wanted to add something to a previous issue but it was already closed.
In that issue I mentioned an example I created (a C scanner) and you asked whether I could post the code.

I did some more testing using the C scanner and it failed on several inputs. Apart from it failing on certain inputs the scanner is written in FreeBASIC which makes it less usable as an example that could be included in libphorward. I am willing and able to translate the example scanner to C when I get it to scan most C code (I have to do some serious testing before I can say that I created anything close to a scanner that can tokenize C code). 

The question is related to what to do when I find typos in some part of libphorward (either the manual or the source code). To me a typo is not really an 'issue', not something I'd want to create an issue for.
But minimization of the number of typos in manuals  and source code seems to me to be a good thing.  

Is there some way I can notify you of typos without having to create an issue? I'd prefer to create issues only for 'real'  bugs and not for typos.

**Comment by phorward** [comment]
Hello @FreeBASIC-programmer, so am I right, you're using the plex-tools from libphorward via a FreeBASIC program? That sounds neat, and in my opinion, its OK for me if you just push the FreeBASIC code here. 

Well, the simplest way to correct typos without opening new issues is if you just do pull requests to the project. git clone the source code, do your changes and then push it right back with a pull request. That's the way it is meant to be and the best in my opinion.

Currently, I'm working hard on rewriting the parsing tools of libphorward to use it as a base for UniCC v2 soon. What about a FreeBASIC target for UniCC, just to also add some code written by you in a language you are familar with?

Bye, Jan

**Comment by FreeBASIC-programmer** [comment]
A FreeBASIC target for UniCC sounds like a very good idea. I had a look at the UniCC repository. Creating a FreeBASIC target involves the following steps:

- translate files in unicc/targets/C.source to FreeBASIC
- run script (awk)
- (almost) done 

I've already started translating the code in unicc/targets/C.source. There does not seem to be a lot of code in unicc/targets/C.source. If creating a FreeBASIC target is as straightforward as I think it is I should have a working target by the end of this week (if not sooner).

**Comment by FreeBASIC-programmer** [comment]
It's taking me a bit longer than expected to get the translation of the C code right (UniCC).
A couple more files to go and then it's testing time. 

I've also managed to translate a program written in FreeBASIC that, given a state machine (created by plex), generates a file in graphviz format. Using the dot tool you get a nice picture of the state machine.
The example shown here is a .dot file representing a state machine created for a list of keywords (wstring, zstring,wstr,str,bling,wing). The machine was creating using calls to plex_define for each and every keyword. All keywords have a unique ID.
```
digraph {
 rankdir=LR;
 node [shape = circle];
 n0 [label = " n0\nmatch_flags 0\nref_flags 0"];
 n0 -> n1 [label = <&#x62; - &#x62;>];
 n0 -> n2 [label = <&#x73; - &#x73;>];
 n0 -> n3 [label = <&#x77; - &#x77;>];
 n0 -> n4 [label = <&#x7A; - &#x7A;>];
 n1 [label = " n1\nmatch_flags 0\nref_flags 0"];
 n1 -> n5 [label = <&#x6C; - &#x6C;>];
 n2 [label = " n2\nmatch_flags 0\nref_flags 0"];
 n2 -> n6 [label = <&#x74; - &#x74;>];
 n3 [label = " n3\nmatch_flags 0\nref_flags 0"];
 n3 -> n7 [label = <&#x69; - &#x69;>];
 n3 -> n8 [label = <&#x73; - &#x73;>];
 n4 [label = " n4\nmatch_flags 0\nref_flags 0"];
 n4 -> n9 [label = <&#x73; - &#x73;>];
 n5 [label = " n5\nmatch_flags 0\nref_flags 0"];
 n5 -> n10 [label = <&#x69; - &#x69;>];
 n6 [label = " n6\nmatch_flags 0\nref_flags 0"];
 n6 -> n11 [label = <&#x72; - &#x72;>];
 n7 [label = " n7\nmatch_flags 0\nref_flags 0"];
 n7 -> n12 [label = <&#x6E; - &#x6E;>];
 n8 [label = " n8\nmatch_flags 0\nref_flags 0"];
 n8 -> n13 [label = <&#x74; - &#x74;>];
 n9 [label = " n9\nmatch_flags 0\nref_flags 0"];
 n9 -> n14 [label = <&#x74; - &#x74;>];
 n10 [label = " n10\nmatch_flags 0\nref_flags 0"];
 n10 -> n15 [label = <&#x6E; - &#x6E;>];
 n11 [shape=doublecircle,label = " n11\nmatch_flags 0\nref_flags 0\nID 5"];
 n11 -> n16 [label = <&#x69; - &#x69;>];
 n12 [label = " n12\nmatch_flags 0\nref_flags 0"];
 n12 -> n17 [label = <&#x67; - &#x67;>];
 n13 [label = " n13\nmatch_flags 0\nref_flags 0"];
 n13 -> n18 [label = <&#x72; - &#x72;>];
 n14 [label = " n14\nmatch_flags 0\nref_flags 0"];
 n14 -> n19 [label = <&#x72; - &#x72;>];
 n15 [label = " n15\nmatch_flags 0\nref_flags 0"];
 n15 -> n20 [label = <&#x67; - &#x67;>];
 n16 [label = " n16\nmatch_flags 0\nref_flags 0"];
 n16 -> n21 [label = <&#x6E; - &#x6E;>];
 n17 [shape=doublecircle,label = " n17\nmatch_flags 0\nref_flags 0\nID 7"];
 n18 [shape=doublecircle,label = " n18\nmatch_flags 0\nref_flags 0\nID 4"];
 n18 -> n22 [label = <&#x69; - &#x69;>];
 n19 [label = " n19\nmatch_flags 0\nref_flags 0"];
 n19 -> n23 [label = <&#x69; - &#x69;>];
 n20 [shape=doublecircle,label = " n20\nmatch_flags 0\nref_flags 0\nID 6"];
 n21 [label = " n21\nmatch_flags 0\nref_flags 0"];
 n21 -> n24 [label = <&#x67; - &#x67;>];
 n22 [label = " n22\nmatch_flags 0\nref_flags 0"];
 n22 -> n25 [label = <&#x6E; - &#x6E;>];
 n23 [label = " n23\nmatch_flags 0\nref_flags 0"];
 n23 -> n26 [label = <&#x6E; - &#x6E;>];
 n24 [shape=doublecircle,label = " n24\nmatch_flags 0\nref_flags 0\nID 3"];
 n25 [label = " n25\nmatch_flags 0\nref_flags 0"];
 n25 -> n27 [label = <&#x67; - &#x67;>];
 n26 [label = " n26\nmatch_flags 0\nref_flags 0"];
 n26 -> n28 [label = <&#x67; - &#x67;>];
 n27 [shape=doublecircle,label = " n27\nmatch_flags 0\nref_flags 0\nID 1"];
 n28 [shape=doublecircle,label = " n28\nmatch_flags 0\nref_flags 0\nID 2"];
}
```
The resulting picture after running dot (dot -Tsvg keywords.dot -o keywords.svg).
https://github.com/FreeBASIC-programmer/pictures/blob/master/keywords.svg

To see the full size image right click on image and select "view image". The result is a rather large image. 
There are some .dot file viewers out there that make viewing a large state machine a bit more comfortable (zgrviewer is a good too to view .dot files).

The program that turns a state machine generated by plex into a .dot file is already done (just needs some testing to make sure the C code is ok). I'll put that up sometime tomorrow. It would be interesting to see whether I can come up with something similar for state machines generated by the parser generator (something like https://graphviz.gitlab.io/_pages/Gallery/directed/psg.svg).

Finishing the FreeBASIC backend for UniCC will take a lot more time than I initially thought it would.
And I am pretty sure I will not be able to add the backend to UniCC without your help. When it comes to codegenerators the devil is in the detail.

**Comment by phorward** [comment]
Hello @FreeBASIC-programmer,

you had been very busy and done many cool things to both projects, thank you for the updates 👍! The visual representation of the DFA state machine looks awesome, and it won't be a problem to do this also for the LR & LALR parser generator. I'm very excited on your new tool!

I've also done several updates to the "rework" branch of the phorward project, and hope that this will face the way to do UniCC v2 soon. I'm thinking about writing this in C++, especially because I want to get more familar with this language. (Maybe I never get any more chance to write C++ in my professional work, there I'm totally with Python now...)

Creating new parser templates is sometimes a hard way testing the several results. Doing the primary code generation is easy, you just need to write down the tlt file. The [Python target](https://github.com/phorward/unicc/blob/develop/targets/python.tlt) may be easier to adapt for FreeBASIC because it follows the much simpler Python syntax. Maybe you can grab some things also there? Please do also read the README in https://github.com/phorward/unicc/tree/develop/targets to start creating tlt files.

Keep up the great work, I'm very pleased!

So long,
Jan

**Comment by FreeBASIC-programmer** [comment]
I've finished the C version of the visual representation of the state machine. Code can be found at the end of this comment. 

I finished the translation of the C code to FreeBASIC (UniCC).  FreeBASIC is more like C than it is like Python. I don't know whether it would be that easy to translate Python code to FreeBASIC. 
I should get the FreeBASIC template code working in the upcoming week.

```c
#include "phorward.h"

#define SIZE (lex->trans[i][0])
#define FROM (lex->trans[i][j])
#define TO   (lex->trans[i][j+1])
#define DST  (lex->trans[i][j+2])
#define MATCH_FLAGS (lex->trans[i][2])
#define REF_FLAGS (lex->trans[i][3])
#define FINAL_STATE (lex->trans[i][1] > 0)
#define ID (lex->trans[i][1])
#define DEFAULT_TRANSITION (lex->trans[i][4] != lex->trans_cnt)

void write_edge(FILE* transitions, wchar_t from, wchar_t to);
int write_dfa(plex *lex, char* filename);

void write_edge(FILE* transitions, wchar_t from, wchar_t to)
{  
  if (iswprint(from)) 
    fprintf(transitions,"&#x%x;",from);
  else
    fprintf(transitions,"0x%x",from);
  if (to != from)
  {
    if (iswprint(to))
      fprintf(transitions," - &#x%x;",to);
    else
      fprintf(transitions," - 0x%x",to);
  };
};

int write_dfa(plex *lex, char* filename)
{
  int i,j;
  FILE *transitions;
  int dst;
  
  if (strlen(filename) == 0) 
    return -1;
  transitions = fopen(filename,"w+b");
  if (transitions == 0)
    return -1;
    
  /* write start of graph */
  fprintf(transitions,"digraph {\n");
  fprintf(transitions,"  rankdir=LR;\n");
  fprintf(transitions,"  node [shape = circle];\n");

  for (i = 0;i < lex->trans_cnt;i++)
  {
    /* size = lex->trans[i][0]; */
    fprintf(transitions,"  n%d [",i);
    /* change shape and label of node if state is a final state */
    if (FINAL_STATE)
      fprintf(transitions,"shape=doublecircle,");
    fprintf(transitions,"label = \" n%d\\nmatch_flags = %d\\nref_flags = %d\\n",i,MATCH_FLAGS,REF_FLAGS);
    if (FINAL_STATE)
      fprintf(transitions,"id = %d\\n", ID);
    fprintf(transitions,"\"];\n");
    /* default transition */
    if (DEFAULT_TRANSITION) 
      fprintf(transitions,"  n%d -> n%d [style=bold];\n",i,lex->trans[i][4]);
    /* a state with size < 5 is a final state: it has no outgoing transitions */
    if (SIZE > 5)
    {
      j = 5;
      while (1)
      {
        fprintf(transitions,"  n%d -> n%d [label = <",i,DST);
        write_edge(transitions,FROM,TO);
        dst = lex->trans[i][j+2];
        j += 3;
        while (1) 
        {
          /*  no more transitions to write */
          if (j >= SIZE)
          {
            fprintf(transitions,">];\n");
            break;
          };
          if (lex->trans[i][j+2] == dst)
          {
            fprintf(transitions,"<br/>");
            write_edge(transitions,FROM,TO);            
            j += 3;
            continue;
          };
          /* no more transitions to write */
          fprintf(transitions,">];\n");
          break;
        };
        if (j >= SIZE)
          break;
      };
    };
  };
  fprintf(transitions,"}\n");
  fclose(transitions);
  return 0;
};

int main (int argc, char** argv)
{
  int i;
  plex *s;
  pregex_ptn *err_; 
  int err;

  enum
  {
    ID1 = 1,
    ID2 = 2,
    ID3 = 3,
    ID4 = 4,
    ID5 = 5,
    ID6 = 6,
    ID7 = 7
  };
  
  struct 
  {
    char* pat;
    int id;
    int flags;
  } patterns[] =  
  {
    {"wstring",ID1,PREGEX_COMP_STATIC},
    {"zstring",ID2,PREGEX_COMP_STATIC},
    {"string",ID3,PREGEX_COMP_STATIC},
    {"wstr",ID4,PREGEX_COMP_STATIC},
    {"str",ID5,PREGEX_COMP_STATIC},
    {"bling",ID6,PREGEX_COMP_STATIC},
    {"wing",ID7,PREGEX_COMP_STATIC},
    {"keywords.dot",0,-1},
    {"_[a-zA-Z0-9_]+",ID1,0},
    {"[a-zA-Z][a-zA-Z0-9_]*",ID1,0},        
    {"identifier.dot",0,-1},
    {"abc.*def.*ghi",ID1,0},
    {"large.dot",0,0},
    {"",-1,-1}
  };
  
  i = 0;
  while (1)
  {
    s =  plex_create(0);
    if (s == 0) 
    {
      fprintf(stderr,"Could not create lexical analyzer, exiting");
      return -1;
    };
    while (patterns[i].id != 0)  
    {
      err_ = plex_define(s,patterns[i].pat,patterns[i].id,patterns[i].flags);
      if (err_ == 0)
      {
        fprintf(stderr,"Problem while creating pattern, exiting");
        plex_free(s);
        return -1;
      };
      i++;
    };
    err = plex_prepare(s);  
    if (err == 0)
    {
      fprintf(stderr,"Could not generate dfa");
      plex_free(s);
      return -1;
    };
    err = write_dfa(s,patterns[i].pat);
    if (err)
    {
      fprintf(stderr,"Could not create file %s",patterns[i].pat);
      plex_free(s);
      return -1;
    };      
    plex_free(s);
    i++;
    if (patterns[i].id == -1 && patterns[i].flags == -1)
      return 0;    
  };
};
```

**Comment by phorward** [comment]
Thanks, looks very cool and interesting.

I would like to bring some dynamic inside this and would integrate it into the library as a demo program (what about plexdot, or plex with a dot output option?)
